### ISSUE TITLE
arduino mini pro, NR2483 and Orange LoraWAN

### ISSUE THREAD

**Issue by fhenryco** [Orange-OpenSource/Orange-ExpLoRer-Kit-for-LoRa#1]
Hello,

I have NR2483 and my own arduinos (mini pro , nanos, ...) . Already tested succesfully the point to point Lora transmissions.

 I want to connect to Orange LoraWAN (i have an account) but i can't use the sketches and libraries here because it's not the Orange explorer kit that i have. I tried to compile for pro mini just the provided example to extract the device EUI  but already at this level SerialUSB gives problems.

If there is only few modifications needed in the library may be i could do it ... but i doubt this will be the case.

So where could i find sketches for arduino mini pro to interact with my NR2483 and the complete MAC protocol to connect to Orange LoraWAN ?

Thanks in advance

**Comment by laurentchivot** [comment]
Hello, on the LoRa Explorer board, the microcontroller talks to the RN2483 as describded at https://support.sodaq.com/Boards/ExpLoRer/
The SODAQ ExpLoRer has 4 hardware serials:
SerialUSB – This is for when you are debugging over the USB Cable.
Serial – Serial is attached to pin D1/TX and D0/RX.
Serial1 – Is connected to the Bluetooth Module.
Serial2 – Is connected to the RN2483 LoRaWAN Module.

Our Library implements that , if you want to use simpler arduino boards, you have to adapt the serial name to the one your're using on your board

**Comment by laurentchivot** [comment]
Regards
